## 
## SAMPLE VALUES.YAML FILE
## 

deployment: true
service: true
gateway: true
virtualService: true
destinationRule: true

name: go-webserver
namespace: go-webserver

targetPort: 8080
exposedPort: 80
image: localhost:5001/go-webserver:v0.0.1
replicas: 3
hosts: 
  - go-webserver.example.com

readinessProbe:
  path: "/ready"
  initialDelaySeconds: 5
  periodSeconds: 10

custom-header-value: 
  x-trv-heritage: go-webserver

uris:
  - /hotels
  - /health
  - /ready
  - /metrics

namespaceLabels:
  istio-injection: enabled