deployment: true
service: true
gateway: true
virtualService: true
destinationRule: true

name: webserver
namespace: app

targetPort: 9999
exposedPort: 80
image: localhost:5001/app-webserver:v1.0.0
replicas: 15
hosts: 
  - webserver.example.com

readinessProbe:
  path: "/ready"
  initialDelaySeconds: 5
  periodSeconds: 10

uris:
  - /hotels
  - /health
  - /ready
  - /metrics

labels:
  istio-injection: enabled