{{ if eq .Values.gateway true }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.exposedPort }}
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.hosts }}
    - {{ . }}
    {{- end }}
{{ end }}