apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels: 
  {{- range $key, $value := .Values.namespaceLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install