{{ if eq .Values.virtualService true }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range .Values.hosts }}
  - {{ . }}
  {{- end }}
  gateways:
  - {{ .Values.name }}-gateway
  http:
  - match:
    {{- range .Values.uris }}
    - uri:
        prefix: {{ . }}
    {{- end }}
    route:
    - destination:
        port:
          number: {{ .Values.exposedPort }}
        host: {{ .Values.name }}-service
      headers:
        response:
          add:
            {{- range $key, $value := .Values.customHeader }}
            {{ $key }}: {{ $value }}
            {{- end }}
{{ end }}